import { z } from 'zod'; import { getDb, saveDb } from '../../src/data/store.mjs'; import { publicDeal } from '../../src/domain/schema.mjs'; import { attentionRequired, pipelineMetrics, getDataCompleteness } from '../../src/services/selectors.mjs'; import { audit } from '../audit/auditLog.mjs';
function assertSession(session){if(!session){const err=new Error('unauthorized'); err.status=401; throw err}} function limitedDeal(deal){const d=publicDeal(deal); return {reference:d.reference,name:d.name,stage:d.stage,investment_decision:d.investment_decision,asking_price_eur:d.asking_price_eur,total_project_cost_eur:d.total_project_cost_eur,units:d.units,yoc:d.yoc,exit_yield:d.exit_yield,spread_bps:d.spread_bps,owner_user_id:d.owner_user_id,next_action:d.next_action,next_action_due_date:d.next_action_due_date,migration_status:d.migration_status,data_quality_issues:d.data_quality_issues}}
export const toolSchemas={search_deals:z.object({query:z.string().default(''),stage:z.string().optional(),investment_decision:z.string().optional()}),get_deal:z.object({reference:z.string()}),get_pipeline_metrics:z.object({}),get_overdue_tasks:z.object({}),get_data_quality_issues:z.object({}),compare_deals:z.object({references:z.array(z.string()).min(2)}),validate_deal_metrics:z.object({reference:z.string()}),create_task:z.object({deal_reference:z.string().nullable(),title:z.string(),due_date:z.string().nullable(),confirmed:z.boolean().default(false)}),update_deal:z.object({reference:z.string(),patch:z.record(z.string(),z.unknown()),confirmed:z.boolean().default(false),justification:z.string().optional()}),add_interaction:z.object({deal_reference:z.string().nullable(),note:z.string(),confirmed:z.boolean().default(false)}),link_contact_to_deal:z.object({reference:z.string(),contact_id:z.string(),role:z.enum(['originator','owner','advisor','lender','other']),confirmed:z.boolean().default(false)}),generate_ic_summary:z.object({reference:z.string()}),draft_followup_email:z.object({reference:z.string(),recipient_hint:z.string().optional()})};
export function runTool(name,input,session){assertSession(session); if(!toolSchemas[name]){const err=new Error('unknown_tool'); err.status=404; throw err} const args=toolSchemas[name].parse(input??{}), db=getDb(); audit({tool:name,user:session.user,input:args});
 if(name==='search_deals'){const q=args.query.toLowerCase(); return {cutoff:db.generated_at,results:db.deals.filter(d=>(!q||`${d.reference} ${d.name} ${d.source??''}`.toLowerCase().includes(q))&&(!args.stage||d.stage===args.stage)&&(!args.investment_decision||d.investment_decision===args.investment_decision)).slice(0,50).map(limitedDeal)}}
 if(name==='get_deal'){const d=db.deals.find(x=>x.reference===args.reference); if(!d)return {error:'not_found'}; return {cutoff:db.generated_at,deal:limitedDeal(d),documents:db.documents.filter(doc=>doc.deal_id===d.id),tasks:db.tasks.filter(t=>t.deal_id===d.id),data_completeness:getDataCompleteness(d)}}
 if(name==='get_pipeline_metrics')return {cutoff:db.generated_at,metrics:pipelineMetrics(db)}; if(name==='get_overdue_tasks')return {cutoff:db.generated_at,overdue_tasks:attentionRequired(db).overdue_tasks}; if(name==='get_data_quality_issues')return {cutoff:db.generated_at,issues:attentionRequired(db).migrations_needing_review.map(limitedDeal)}; if(name==='compare_deals')return {cutoff:db.generated_at,deals:args.references.map(r=>db.deals.find(d=>d.reference===r)).filter(Boolean).map(limitedDeal)}; if(name==='validate_deal_metrics'){const d=db.deals.find(x=>x.reference===args.reference); return {cutoff:db.generated_at,reference:args.reference,valid:!!d,data_completeness:d?getDataCompleteness(d):null,missing:d?getDataCompleteness(d).missing:['deal_not_found']}}
 if(['create_task','update_deal','add_interaction','link_contact_to_deal'].includes(name)&&!args.confirmed)return {requires_confirmation:true,message:'Human confirmation required before CRM write',proposed_change:args};
 if(name==='create_task'){const d=args.deal_reference?db.deals.find(x=>x.reference===args.deal_reference):null; const task={id:`task_${Date.now()}`,deal_id:d?.id??null,title:args.title,due_date:args.due_date,status:'open',owner_user_id:session.user,created_at:new Date().toISOString(),updated_at:new Date().toISOString()}; db.tasks.push(task); saveDb(db); return {ok:true,task}}
 if(name==='update_deal'){const d=db.deals.find(x=>x.reference===args.reference); if(!d)return {error:'not_found'}; const before={}; for(const k of Object.keys(args.patch))before[k]=d[k]; Object.assign(d,args.patch,{updated_at:new Date().toISOString()}); saveDb(db); audit({tool:name,user:session.user,before,after:args.patch,justification:args.justification??null}); return {ok:true,before,after:args.patch}}
 if(name==='add_interaction'){const interaction={id:`int_${Date.now()}`,deal_id:args.deal_reference?(db.deals.find(d=>d.reference===args.deal_reference)?.id??null):null,contact_id:null,note:args.note,created_at:new Date().toISOString(),created_by:session.user}; db.interactions.push(interaction); saveDb(db); return {ok:true,interaction}}
 if(name==='link_contact_to_deal'){const d=db.deals.find(x=>x.reference===args.reference); if(!d)return {error:'not_found'}; db.deal_contacts.push({deal_id:d.id,contact_id:args.contact_id,role:args.role}); saveDb(db); return {ok:true}}
 if(name==='generate_ic_summary'){const d=db.deals.find(x=>x.reference===args.reference); if(!d)return {error:'not_found'}; return {cutoff:db.generated_at,summary:{reference:d.reference,facts:limitedDeal(d),missing_data:getDataCompleteness(d).missing,inference:'No se inventan métricas; revisar datos ausentes antes de IC final.'}}}
 if(name==='draft_followup_email'){const d=db.deals.find(x=>x.reference===args.reference); if(!d)return {error:'not_found'}; return {subject:`Seguimiento ${d.reference} — ${d.name}`,body:`Hola,\n\nSeguimos revisando ${d.name}. Próximo paso interno: ${d.next_action??'pendiente de definir'}.\n\nGracias,`}}
}
