export function isActiveDeal(deal){return !['closed_won','closed_lost','archived'].includes(deal.stage)}
export function getDealStage(deal){return deal.stage} export function getInvestmentDecision(deal){return deal.investment_decision}
export function getDealVolume(deal){return deal.total_project_cost_eur??deal.acquisition_price_eur??deal.asking_price_eur??null} export function getSpreadBps(deal){return deal.spread_bps}
export function getDaysSinceUpdate(deal,now=new Date()){const dt=new Date(deal.updated_at); return Number.isNaN(dt.getTime())?null:Math.floor((now-dt)/86400000)}
export function getTaskUrgency(task,now=new Date()){if(task.status!=='open')return 'closed'; if(!task.due_date)return 'no_due_date'; const today=now.toISOString().slice(0,10); if(task.due_date<today)return 'overdue'; if(task.due_date===today)return 'due_today'; return 'upcoming'}
export function getDataCompleteness(deal){const required=['stage','investment_decision','owner_user_id','next_action','next_action_due_date']; const missing=required.filter(k=>deal[k]===null||deal[k]===undefined||deal[k]==='unclassified'||deal[k]==='unreviewed'); const numeric=['asking_price_eur','units','yoc','exit_yield','spread_bps']; const missingNumeric=numeric.filter(k=>deal[k]===null||deal[k]===undefined); return {score:Math.max(0,1-(missing.length+missingNumeric.length)/(required.length+numeric.length)),missing:missing.concat(missingNumeric)}}
export function getRelationshipHealth(companyId,db){const contacts=db.contacts.filter(c=>c.company_id===companyId); const linked=new Set(db.deal_contacts.filter(dc=>contacts.some(c=>c.id===dc.contact_id)).map(dc=>dc.deal_id)); return {company_id:companyId,contacts:contacts.length,linked_deals:linked.size,health:linked.size>2?'strong':linked.size>0?'active':'cold'}}
export function getWeightedPipelineValue(deals){const weights={go:.65,conditional_go:.45,borderline:.25,unreviewed:.1,no_go:0}; return deals.filter(isActiveDeal).reduce((sum,d)=>sum+((getDealVolume(d)??0)*(weights[d.investment_decision]??0)),0)}
export function attentionRequired(db,now=new Date()){const active=db.deals.filter(isActiveDeal); return {overdue_tasks:db.tasks.filter(t=>getTaskUrgency(t,now)==='overdue'),deals_without_next_action:active.filter(d=>!d.next_action),deals_without_owner:active.filter(d=>!d.owner_user_id),critical_data_incomplete:active.filter(d=>getDataCompleteness(d).score<.6),migrations_needing_review:db.deals.filter(d=>d.migration_status==='needs_review'),stale_deals:active.filter(d=>(getDaysSinceUpdate(d,now)??0)>15)}}
export function pipelineMetrics(db){const active=db.deals.filter(isActiveDeal); return {total:db.deals.length,active:active.length,closed_lost:db.deals.filter(d=>d.stage==='closed_lost').length,closed_won:db.deals.filter(d=>d.stage==='closed_won').length,archived:db.deals.filter(d=>d.stage==='archived').length,go:active.filter(d=>d.investment_decision==='go').length,conditional_go:active.filter(d=>d.investment_decision==='conditional_go').length,borderline:active.filter(d=>d.investment_decision==='borderline').length,weighted_pipeline_value_eur:getWeightedPipelineValue(db.deals)}}
