import { describe,it,expect,beforeEach,afterEach } from 'vitest'; import request from 'supertest'; import fs from 'node:fs'; import path from 'node:path'; import { createApp } from '../../server/index.mjs'; import { saveDb } from '../../src/data/store.mjs'; import { resetSessionsForTests } from '../../server/auth/session.mjs';
const dbPath=path.resolve('private/test/crm.json'); const sampleDb={generated_at:'2026-07-15T00:00:00Z',manifest:{},deals:[{id:'d1',reference:'MAGG-1',name:'Deal 1',stage:'underwriting',investment_decision:'conditional_go',asking_price_eur:100,acquisition_price_eur:null,total_project_cost_eur:null,capex_eur:null,noi_eur:null,ebitda_eur:null,units:null,sqm:null,yoc:null,exit_yield:null,spread_bps:null,levered_irr:null,unlevered_irr:null,equity_multiple:null,assumption_notes:null,investment_thesis:null,owner_user_id:null,originator_company_id:null,originator_contact_id:null,next_action:null,next_action_due_date:null,source:null,source_updated_at:null,created_at:'2026-07-15',updated_at:'2026-07-15T00:00:00Z',migration_status:'clean',data_quality_issues:[],legacy_raw:{secret:'x'}}],companies:[],contacts:[],deal_contacts:[],documents:[],tasks:[],interactions:[],migration_report:{}};
beforeEach(()=>{process.env.MAGG_CRM_DB=dbPath; process.env.MAGG_CRM_PASSWORD='test-password-12345'; process.env.CRM_ALLOWED_ORIGINS='https://allowed.example'; fs.mkdirSync(path.dirname(dbPath),{recursive:true}); saveDb(sampleDb,dbPath); resetSessionsForTests()}); afterEach(()=>resetSessionsForTests());
describe('authenticated API',()=>{
 it('denies private endpoints without session',async()=>{const app=createApp(); for(const url of ['/api/deals','/api/brokers','/api/documents']){const res=await request(app).get(url); expect(res.status).toBe(401); expect(JSON.stringify(res.body)).not.toContain('Deal 1')} const write=await request(app).post('/api/tools/update_deal').send({}); expect(write.status).toBe(401)});
 it('rejects unauthorized CORS origins',async()=>{const app=createApp(); const res=await request(app).get('/api/deals').set('Origin','https://unauthorized.example'); expect(res.status).toBe(403); expect(res.headers['access-control-allow-origin']).toBeUndefined()});
 it('serves canonical counts consistently after login and strips legacy raw',async()=>{const app=createApp(); const agent=request.agent(app); await agent.post('/api/auth/login').send({password:'test-password-12345'}).expect(200); const deals=await agent.get('/api/deals').expect(200); const metrics=await agent.get('/api/pipeline/metrics').expect(200); const tool=await agent.post('/api/tools/get_pipeline_metrics').send({}).expect(200); expect(deals.body.deals).toHaveLength(metrics.body.metrics.total); expect(tool.body.metrics.total).toBe(metrics.body.metrics.total); expect(JSON.stringify(deals.body)).not.toContain('legacy_raw')});
 it('requires confirmation for Hermes writes',async()=>{const app=createApp(); const agent=request.agent(app); await agent.post('/api/auth/login').send({password:'test-password-12345'}); const res=await agent.post('/api/tools/update_deal').send({reference:'MAGG-1',patch:{stage:'closing'}}).expect(200); expect(res.body.requires_confirmation).toBe(true)});
});
