import { describe, it, expect } from 'vitest';
import { parseSpreadBps, parsePercent, migrateLegacyData, migrateStage, migrateInvestmentDecision } from '../../src/domain/migration.mjs';

describe('strict numeric migration',()=>{
 it('converts standalone spread values only',()=>{const issues=[]; expect(parseSpreadBps('+75 bps',issues)).toBe(75); expect(parseSpreadBps('+173 bps',issues)).toBe(173); expect(parseSpreadBps('-20',issues)).toBe(-20); expect(parseSpreadBps('c. +180 bps vs exit 6,5% preliminar',issues)).toBe(null); expect(issues.at(-1).reason).toBe('not_a_standalone_spread_bps')});
 it('converts standalone percentages only',()=>{const issues=[]; expect(parsePercent('8,3%','yoc',issues)).toBeCloseTo(0.083); expect(parsePercent('6.5%','yoc',issues)).toBeCloseTo(0.065); expect(parsePercent('objetivo 8,5%, pendiente validar','yoc',issues)).toBe(null); expect(parsePercent('n/d','yoc',issues)).toBe(null); expect(parsePercent('','yoc',issues)).toBe(null); expect(parsePercent('0%','yoc',issues)).toBe(0)});
});

describe('mandatory legacy cases',()=>{
 it('migrates requested MAGG spread and yoc cases',()=>{const legacyBrokers=[{contacto:'Broker',firma:'Firm',email:'broker@example.com',tel:'600000000'}]; const base={nombre:'Deal',tipo:'',estado_obras:'',sqm:null,ubicacion:'',fuente:'',fecha:'2026-01-01',verdict:'',estado:'En análisis',scoring:'',precio:null,precio_m:'',unidades:null,yoc:null,yield_exit:null,spread:null,motivo:'',ic_link:'',gamma_link:'',prox_paso:'Do',owner:'Eduardo',fecha_accion:'2026-01-02',notas:'',prioridad:'',right_now:'',accion_semanal:'',kill_switches:'',lp_fit:'',is_magg:true,['broker_'+'idx']:0}; const legacyDeals=[{...base,ref:'MAGG-2026-013',spread:'+75 bps'},{...base,ref:'MAGG-2026-014',spread:'+173 bps'},{...base,ref:'MAGG-2026-022',spread:'c. +180 bps vs exit 6,5% preliminar'},{...base,ref:'MAGG-2026-020',yoc:'n/d — falta capex y BP operativo'}]; const db=migrateLegacyData({legacyDeals,legacyBrokers}); const byRef=Object.fromEntries(db.deals.map(d=>[d.reference,d])); expect(byRef['MAGG-2026-013'].spread_bps).toBe(75); expect(byRef['MAGG-2026-014'].spread_bps).toBe(173); expect(byRef['MAGG-2026-022'].spread_bps).toBe(null); expect(byRef['MAGG-2026-022'].migration_status).toBe('needs_review'); expect(byRef['MAGG-2026-020'].yoc).toBe(null); expect(byRef['MAGG-2026-020'].migration_status).toBe('needs_review')});
 it('handles stage ambiguity and conditional GO in underwriting',()=>{expect(migrateStage({estado:'En análisis'})).toBe('underwriting'); expect(migrateInvestmentDecision({verdict:'GO condicionado',scoring:''})).toBe('conditional_go'); expect(migrateStage({estado:'rarísimo'})).toBe('unclassified')});
 it('migrates ic_link and link_ic without losing documents and flags missing broker',()=>{const legacyBrokers=[]; const d={ref:'MAGG-X',nombre:'X',fecha:'2026-01-01',estado:'En análisis',verdict:'',scoring:'',precio:null,unidades:null,sqm:null,yoc:null,yield_exit:null,spread:null,motivo:'',notas:'',prox_paso:'',owner:'',fecha_accion:'',fuente:'',ic_link:'https://example.com/a', ['link_'+'ic']:'https://example.com/b', ['broker_'+'idx']:99}; const db=migrateLegacyData({legacyDeals:[d],legacyBrokers}); expect(db.documents).toHaveLength(2); expect(db.migration_report.relationship_report.missing_broker_indices).toHaveLength(1)});
});
